spring.application.name=scraper-marches

# Paramètres du Scraper
scraper.acheteur-cible=POSTE MAROC
scraper.limite-resultats=5
# Si tu veux tout récupérer sans limite, tu pourras mettre -1
# Configuration MongoDB Atlas
# Remplace <username>, <password>, <cluster-url> et <dbname> par tes vraies valeurs.
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=marches_publics_db

# (Optionnel) Pour afficher les requêtes MongoDB dans les logs, très pratique pour le débogage
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG