spring.application.name=scraper-marches

# Paramètres du Scraper
scraper.acheteur-cible=MINISTERE DE L'ECONOMIE, ET DES FINANCES
scraper.limite-resultats=10
# Si tu veux tout récupérer sans limite, tu pourras mettre -1
# Configuration MongoDB Atlas
# Remplace <username>, <password>, <cluster-url> et <dbname> par tes vraies valeurs.
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=marches_publics_db

# --- Désactivé en prod pour sécurité ---
# logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Configuration Serveur Mail (Lot 1 : Pour les alertes J-7 / J-1)
# Il faudra remplacer par tes vrais identifiants Gmail (ou autre SMTP) et un mot de passe d'application
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=aa2a668e3b7a4a
spring.mail.password=a4458c597b4280
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- Configurations de Sécurité (Production) ---
# En production, ces valeurs doivent être injectées via des variables d'environnement
# ex: export JWT_SECRET=ma_cle_tres_secrete
app.jwt.secret=${JWT_SECRET:RobotDCE_SecretKey_SuperLongue_QuePersonneNePeutDeviner_2026!}
app.admin.password=${ADMIN_INIT_PASSWORD:admin123}
app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}